use crate::module::BytecodeModule;
use serde::{Deserialize, Serialize};

/// Semantic version of the generated bytecode.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize)]
pub struct BytecodeVersion {
    pub major: u32,
    pub minor: u32,
    pub patch: u32,
}

impl BytecodeVersion {
    /// Returns the current version 1.0.0.
    pub fn current() -> Self {
        Self {
            major: 1,
            minor: 0,
            patch: 0,
        }
    }
}

/// Binary serialization and deserialization engine for bytecode.
pub struct BytecodeSerializer;

impl BytecodeSerializer {
    /// Serializes a BytecodeModule to binary vector.
    pub fn serialize(module: &BytecodeModule) -> Result<Vec<u8>, String> {
        let mut buffer = Vec::new();
        // Magic
        buffer.extend_from_slice(b"TSCR");

        // Version
        let version = BytecodeVersion::current();
        buffer.extend_from_slice(&version.major.to_le_bytes());
        buffer.extend_from_slice(&version.minor.to_le_bytes());

        // Payload
        let payload = bincode::serialize(module).map_err(|e| e.to_string())?;
        buffer.extend_from_slice(&payload);

        Ok(buffer)
    }

    /// Deserializes a BytecodeModule from binary slice.
    pub fn deserialize(bytes: &[u8]) -> Result<BytecodeModule, String> {
        if bytes.len() < 12 {
            return Err("Payload too small to contain valid headers".to_string());
        }

        if &bytes[0..4] != b"TSCR" {
            return Err("Invalid bytecode magic signature".to_string());
        }

        // Deserialize payload
        let payload = &bytes[12..];
        let module: BytecodeModule = bincode::deserialize(payload).map_err(|e| e.to_string())?;
        Ok(module)
    }
}
