[build-system]
requires = ["setuptools>=75", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "techscript-lang"
version = "1.0.6"
description = "TechScript — a simple, friendly programming language."
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
authors = [{ name = "Tanmoy (Tcode-Motion)", email = "sachkaswitch@gmail.com" }]
keywords = ["techscript", "language", "interpreter", "compiler", "txs"]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
]

[project.urls]
Homepage = "https://github.com/Tcode-Motion/techscript"
Repository = "https://github.com/Tcode-Motion/techscript"
Issues = "https://github.com/Tcode-Motion/techscript/issues"

[project.scripts]
tech = "techscript.cli:main"
techscript = "techscript.cli:main"

[tool.setuptools]
package-dir = {"" = "src"}
license-files = ["LICENSE"]

[tool.setuptools.packages.find]
where = ["src"]

