[package]
name = "techscript_stdlib"
version = "0.1.0"
edition = "2021"
description = "Extended modular libraries (io, math, string, file, web) for TechScript 2.0"

[dependencies]
techscript_runtime = { path = "../runtime/runtime" }
serde_json = { workspace = true }
serde = { workspace = true }
indexmap = { version = "2", features = ["serde"] }
