use crate::types::{GlobalId, LocalId, ValueId};
use serde::{Deserialize, Serialize};
use techscript_ast::LiteralVal;

/// Represents operand values in the SSA-friendly IR.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum Value {
    /// Virtual register / temporary value generated by instruction execution.
    Temp(ValueId),
    /// Compile-time constant literal value.
    Const(LiteralVal),
    /// Local variable binding ID.
    Local(LocalId),
    /// Global symbol reference ID.
    Global(GlobalId),
    /// DSL block reference ID.
    DslBlock { kind: String, block_id: u32 },
    /// Null/None representation.
    Null,
}
