; TechScript 2.0 — Windows Installer Script
; Built with Inno Setup 6
; Generated by Antigravity
; Fix: Uses HKCU\Software\Classes for file associations (no admin needed).
;      HKLM entries use noerror flag. Auto-continues on any registry error.

#define AppName      "TechScript"
#define AppVersion   "2.0.0"
#define AppPublisher "TechScript Language Project"
#define AppURL       "https://github.com/Tcode-Motion/TechScript-2.0"
#define AppExeName   "tsc.exe"
#define AppLspExe    "techscript-lsp.exe"
#define SourceDir    "..\target\release"
#define AssetsDir    "..\assets\icons"
#define ExamplesDir  "..\examples"
#define DocsDir      "..\docs"

[Setup]
AppId={{B3A1C2D4-5E6F-7890-ABCD-EF1234567890}
AppName={#AppName}
AppVersion={#AppVersion}
AppVerName={#AppName} {#AppVersion}
AppPublisher={#AppPublisher}
AppPublisherURL={#AppURL}
AppSupportURL={#AppURL}/issues
AppUpdatesURL={#AppURL}/releases

; Install to user's local AppData if no admin, or Program Files if admin
DefaultDirName={autopf}\TechScript
DefaultGroupName=TechScript
AllowNoIcons=no

; Output setup EXE
OutputDir=..\releases\current\installer
OutputBaseFilename=TechScript_Setup

; Compression
Compression=lzma2/ultra64
SolidCompression=yes
InternalCompressLevel=ultra64

; Architecture
ArchitecturesInstallIn64BitMode=x64compatible
ArchitecturesAllowed=x64compatible

; Installer appearance
SetupIconFile={#AssetsDir}\app-icon.ico
WizardStyle=modern
WizardSizePercent=120
DisableWelcomePage=no
LicenseFile=..\LICENSE

; ── KEY FIX: lowest = works without admin, dialog lets user elevate if they want
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline dialog

; PATH and file-type changes
ChangesEnvironment=yes
ChangesAssociations=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "addtopath";     Description: "Add TechScript to system PATH (recommended)"; GroupDescription: "Environment:"
Name: "fileassoc";     Description: "Associate .txs files with TechScript compiler"; GroupDescription: "File Associations:"
Name: "desktopicon";   Description: "Create a Desktop shortcut for TechScript REPL"; GroupDescription: "Shortcuts:"; Flags: unchecked
Name: "startmenuicon"; Description: "Create Start Menu shortcuts"; GroupDescription: "Shortcuts:"

[Files]
; --- Core binaries ---
Source: "{#SourceDir}\tsc.exe";              DestDir: "{app}\bin"; Flags: ignoreversion
Source: "{#SourceDir}\techscript-lsp.exe";   DestDir: "{app}\bin"; Flags: ignoreversion

; --- Standard library ---
Source: "..\stdlib\*";      DestDir: "{app}\stdlib";   Flags: ignoreversion recursesubdirs createallsubdirs

; --- Examples ---
Source: "{#ExamplesDir}\*"; DestDir: "{app}\examples"; Flags: ignoreversion recursesubdirs createallsubdirs

; --- Documentation ---
Source: "{#DocsDir}\*";     DestDir: "{app}\docs";     Flags: ignoreversion recursesubdirs createallsubdirs

; --- Icons ---
Source: "{#AssetsDir}\app-icon.ico";  DestDir: "{app}"; Flags: ignoreversion
Source: "{#AssetsDir}\file-icon.ico"; DestDir: "{app}"; Flags: ignoreversion

; --- License & readme ---
Source: "..\LICENSE";   DestDir: "{app}"; Flags: ignoreversion; DestName: "LICENSE.txt"
Source: "..\README.md"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
; Start Menu
Name: "{group}\TechScript REPL";          Filename: "{app}\bin\tsc.exe"; Parameters: "repl"; WorkingDir: "{userdocs}"; IconFilename: "{app}\app-icon.ico"; Tasks: startmenuicon
Name: "{group}\TechScript Documentation"; Filename: "{app}\docs"; Tasks: startmenuicon
Name: "{group}\Uninstall TechScript";     Filename: "{uninstallexe}"; Tasks: startmenuicon
; Desktop
Name: "{userdesktop}\TechScript REPL";    Filename: "{app}\bin\tsc.exe"; Parameters: "repl"; WorkingDir: "{userdocs}"; IconFilename: "{app}\app-icon.ico"; Tasks: desktopicon

[Registry]
; ── FILE ASSOCIATIONS ────────────────────────────────────────────────────────
; Written to HKCU\Software\Classes — works WITHOUT admin (no Access Denied).
; Windows merges HKCU\Software\Classes into HKCR automatically at runtime.

Root: HKCU; Subkey: "Software\Classes\.txs";                              ValueType: string; ValueName: ""; ValueData: "TechScriptFile"; Tasks: fileassoc; Flags: uninsdeletevalue noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile";                    ValueType: string; ValueName: ""; ValueData: "TechScript Source File"; Tasks: fileassoc; Flags: uninsdeletekey noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\DefaultIcon";        ValueType: string; ValueName: ""; ValueData: "{app}\file-icon.ico,0"; Tasks: fileassoc; Flags: noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\tsc.exe"" ""%1"""; Tasks: fileassoc; Flags: noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\shell\run";          ValueType: string; ValueName: ""; ValueData: "Run with TechScript"; Tasks: fileassoc; Flags: noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\shell\run\command";  ValueType: string; ValueName: ""; ValueData: """{app}\bin\tsc.exe"" run ""%1"""; Tasks: fileassoc; Flags: noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\shell\migrate";      ValueType: string; ValueName: ""; ValueData: "Migrate to TechScript 2.0"; Tasks: fileassoc; Flags: noerror
Root: HKCU; Subkey: "Software\Classes\TechScriptFile\shell\migrate\command"; ValueType: string; ValueName: ""; ValueData: """{app}\bin\tsc.exe"" migrate ""%1"""; Tasks: fileassoc; Flags: noerror

; ── INSTALL METADATA (HKLM if admin, HKCU fallback) ─────────────────────────
; noerror = silently skip if access denied (e.g. no admin elevation)
Root: HKLM; Subkey: "Software\TechScript"; ValueType: string; ValueName: "InstallDir";  ValueData: "{app}";          Flags: uninsdeletekey noerror
Root: HKLM; Subkey: "Software\TechScript"; ValueType: string; ValueName: "Version";     ValueData: "2.0.0";          Flags: noerror
Root: HKLM; Subkey: "Software\TechScript"; ValueType: string; ValueName: "StdLibPath";  ValueData: "{app}\stdlib";   Flags: noerror
; Always-succeeds fallback in HKCU
Root: HKCU; Subkey: "Software\TechScript"; ValueType: string; ValueName: "InstallDir";  ValueData: "{app}";          Flags: uninsdeletekey
Root: HKCU; Subkey: "Software\TechScript"; ValueType: string; ValueName: "Version";     ValueData: "2.0.0"
Root: HKCU; Subkey: "Software\TechScript"; ValueType: string; ValueName: "StdLibPath";  ValueData: "{app}\stdlib"

[Environment]
; Add {app}\bin to PATH. Uses user-level PATH if no admin, system-level if admin.
Name: Path; Value: "{app}\bin"; Tasks: addtopath

[Run]
Filename: "{app}\docs\index.html";  Description: "View TechScript documentation"; Flags: postinstall shellexec skipifsilent unchecked
Filename: "{app}\bin\tsc.exe";      Parameters: "--version"; Description: "Verify installation (tsc --version)"; Flags: postinstall runhidden

[UninstallDelete]
Type: filesandordirs; Name: "{app}\.tsc-cache"

[InstallDelete]
Type: filesandordirs; Name: "C:\Program Files (x86)\TechScript"
Type: filesandordirs; Name: "{localappdata}\Programs\TechScript"

[Code]
// ─────────────────────────────────────────────────────────────────────────────
// NOTE: Registry errors are already suppressed via Flags: noerror in [Registry].
// This code section only handles PATH cleanup on uninstall and setup cleanup.
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// ssInstall cleanup — removes old conflicting installation path from environment
// ─────────────────────────────────────────────────────────────────────────────
procedure CurStepChanged(CurStep: TSetupStep);
var
  OldPath, NewPath, OldBinDir: String;
begin
  if CurStep = ssInstall then
  begin
    OldBinDir := 'C:\Program Files (x86)\TechScript\bin';
    
    // Clean system PATH
    if RegQueryStringValue(HKEY_LOCAL_MACHINE,
        'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
        'Path', OldPath) then
    begin
      NewPath := OldPath;
      StringChangeEx(NewPath, ';' + OldBinDir, '', True);
      StringChangeEx(NewPath, OldBinDir + ';', '', True);
      StringChangeEx(NewPath, OldBinDir,       '', True);
      RegWriteStringValue(HKEY_LOCAL_MACHINE,
        'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
        'Path', NewPath);
    end;

    // Clean user PATH
    if RegQueryStringValue(HKEY_CURRENT_USER,
        'Environment', 'Path', OldPath) then
    begin
      NewPath := OldPath;
      StringChangeEx(NewPath, ';' + OldBinDir, '', True);
      StringChangeEx(NewPath, OldBinDir + ';', '', True);
      StringChangeEx(NewPath, OldBinDir,       '', True);
      RegWriteStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', NewPath);
    end;
  end;
end;

// ─────────────────────────────────────────────────────────────────────────────
// PATH cleanup on uninstall — removes {app}\bin from both system and user PATH
// ─────────────────────────────────────────────────────────────────────────────
procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  OldPath, NewPath, BinDir: String;
begin
  if CurUninstallStep = usPostUninstall then
  begin
    BinDir := ExpandConstant('{app}\bin');

    // Try system PATH (HKLM) first
    if RegQueryStringValue(HKEY_LOCAL_MACHINE,
        'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
        'Path', OldPath) then
    begin
      NewPath := OldPath;
      StringChangeEx(NewPath, ';' + BinDir, '', True);
      StringChangeEx(NewPath, BinDir + ';', '', True);
      StringChangeEx(NewPath, BinDir,       '', True);
      RegWriteStringValue(HKEY_LOCAL_MACHINE,
        'SYSTEM\CurrentControlSet\Control\Session Manager\Environment',
        'Path', NewPath);
    end;

    // Also clean user PATH (HKCU)
    if RegQueryStringValue(HKEY_CURRENT_USER,
        'Environment', 'Path', OldPath) then
    begin
      NewPath := OldPath;
      StringChangeEx(NewPath, ';' + BinDir, '', True);
      StringChangeEx(NewPath, BinDir + ';', '', True);
      StringChangeEx(NewPath, BinDir,       '', True);
      RegWriteStringValue(HKEY_CURRENT_USER, 'Environment', 'Path', NewPath);
    end;
  end;
end;
